### ISSUE TITLE
Ошибка при использовании зарезервированного слова Object в PHP 7+

### ISSUE THREAD

**Issue by bobahvas** [iiifx-production/yii2-autocomplete-helper#3]
Подробное описание изменения php тут:
http://php.net/manual/ru/migration72.incompatible.php

```
object для имен классов
Имя object ранее было мягко зарезервировано с PHP 7.0. Теперь оно полноценное зарезервированное слово, запрещающее использовать его в качестве имени класса, трейта или интерфейса.
```

Изменения в Yii2
https://github.com/yiisoft/yii2/blob/master/framework/CHANGELOG.md

```
Chg #7936: Deprecate yii\base\Object in favor of yii\base\BaseObject for compatibility with PHP 7.2 (rob006, cebe, klimov-paul)
```

Pull Request делать долго, Вам проще будет поменять 2 строчки и выпустить новый релиз.

Исправления в текущем плагине:
https://github.com/iiifx-production/yii2-autocomplete-helper/blob/master/source/Component.php#L13
```
use yii\base\Object; -> use yii\base\BaseObject;
```
https://github.com/iiifx-production/yii2-autocomplete-helper/blob/master/source/Component.php#L15
```
class Component extends Object implements BootstrapInterface -> class Component extends BaseObject implements BootstrapInterface
```

**Comment by iiifx** [comment]
Ок, спасибо. Поправлю

**Comment by iiifx** [comment]
Исправлено. Выпустил версию 2.0.0. Прошу обновиться
